accounts.msg ={cipher} 8aa33f7bc3462273e9c3ecefae60b74f3226c2ada62bdaecec0ac8ba1c928ac2aa63d4c68657d9709f8e0c685ac5e792
accounts.build-version=3

accounts.mailDetails.hostName=prod1-accounts@eazybytes.com
accounts.mailDetails.port=9000
accounts.mailDetails.from=prod1-accounts@eazybytes.com
accounts.mailDetails.subject=Your Account Details from Eazy Bank prod1 Environment

accounts.activeBranches[0]=Mumbai
accounts.activeBranches[1]=London
accounts.activeBranches[2]=Washington
