accounts.msg ={cipher} 4221ee25833a7ada0649f39b6c19940cdba69aa66b862dc49ecae575deee83ef458e47c832637754a932d94743f5fe15a0b1eb43bdb7c496e2a5718d916ed84893680a4b9fe29cc0332fc56c2d127b5a
accounts.build-version=3

accounts.mailDetails.hostName=prod1-accounts@eazybytes.com
accounts.mailDetails.port=9000
accounts.mailDetails.from=prod1-accounts@eazybytes.com
accounts.mailDetails.subject=Your Account Details from Eazy Bank prod1 Environment

accounts.activeBranches[0]=Mumbai
accounts.activeBranches[1]=London
accounts.activeBranches[2]=Washington
