accounts.msg =Welcome to the EazyBank Accounts prod1 application
accounts.build-version=3

accounts.mailDetails.hostName=prod1-accounts@eazybytes.com
accounts.mailDetails.port=9000
accounts.mailDetails.from=prod1-accounts@eazybytes.com
accounts.mailDetails.subject=Your Account Details from Eazy Bank prod1 Environment

accounts.activeBranches[0]=Mumbai
accounts.activeBranches[1]=London
accounts.activeBranches[2]=Washington
