accounts.msg ={cipher} b624b6f4aece8809983b3d9916cb59a803015db7a7812d6dddb2003fe09fd59edb3c24ec37c6dfb9da99ae10587017d9
accounts.build-version=3

accounts.mailDetails.hostName=dev-accounts@eazybytes.com
accounts.mailDetails.port=9000
accounts.mailDetails.from=dev-accounts@eazybytes.com
accounts.mailDetails.subject=Your Account Details from Eazy Bank Dev Environment

accounts.activeBranches[0]=Mumbai
accounts.activeBranches[1]=London
accounts.activeBranches[2]=Washington
